baseurl             = "https://davidhampgonsalves.com"
canonifyurls        = true
contentdir          = "content"
languageCode        = "en-US"
layoutdir           = "layouts"
publishdir          = "public"
author              = "David Hamp-Gonsalves"
title               = "David Hamp-Gonsalves"
theme               = "black-and-light"
FootnoteReturnLinkContents = "â†©"

[[menu.main]]
    name = "GitHub"
    url = "//github.com/davidhampgonsalves"
[[menu.main]]
    name = "Projects"
    url = "/projects/"
[[menu.main]]
    name = "Instagram"
    url = "https://instagram.com/davidhampgonsalves/"
[[menu.main]]
    name = "Linkedin"
    url = "https://www.linkedin.com/in/davidhampgonsalves/"

pygmentscodefences  = true
pygmentsstyle       = "bw"

pluralizelisttitles = false
googleAnalytics     = "UA-123-45"

[permalinks]
posts = ":slug/"

[params]
sitename      = "David Hamp-Gonsalves"
dateform     = "January 2006"
dateformfull = "Mon Jan 2 2006"
